language: c
sudo: false
branches:
  only:
  - master
env:
  global:
    secure: bWkYtgo7M+Z92nmXRLdUPJGc/s585OexV6fbEX9GaOsR+2iV790aIbbLLrzYzYW0UT3XH8bjncBYZRI06+xvC8b1PYKdvjg9gzQ0s7TmptXSxlVcBxiaA25hyuADl2ShMu5+X8mqMrFw8CZJweiAZA3EVfsu5nhmGiTzEOy9jmnHv0ZynCxFHgR6YwB3LmP1gCv04lr4Km2+g3GU8nzRzvKhlRyZepGMWw7lAQLcbPgxN9/cxTapZeKgbiE+osrMuK9E+bNYwS5++CALHZiJfcg6VGNJD+bm5W4zk7DcmYRbOieSFx3bjpWlmu+RdkBpJrMxiU3DE/zi7z4tQFADvnz77hIGSlNHM85RHz8W680Z/r/3BREdqeMpQs/Zlt+25K1u5UCEZnh1IovwDmeqEQMd7acR+O7gWYX7DHiVPuj1Xxd7J16ifWYk9MkaXCJtE0l2MOUfFiq5LyCFoKxe4BZSEs5btFgLhP0IPEKa79hCrsegWk15tNeGMOGVY0trSmdqWxMbnfjQExwpkmCZ82DwY9+kgUMWsoOn/+Yzbzi8ekgf57kTg3r1ULr5qXz389/Z3qU74IvYu2N9EaWeNHt0plGVqctnaF+Ocu5OQJzZONRIPdGAAQf9ibkTOBSIVgcehUP619sf1Px++ZfOtjS+QekinuLJFxAcMpEQXbQ=
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
cache:
  directories:
  - "~/Rlib"
before_script:
  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - echo '.travis.yml' > .Rbuildignore
  - Rscript -e 'sapply(c("devtools", "httpuv", "shiny"), function(x) { if (!(x %in%
    rownames(installed.packages()))) { install.packages(x, dependencies = TRUE) }})'
  - Rscript -e 'if (!("shinyapps" %in% rownames(installed.packages()))) { devtools::install_github(repo
    = "rstudio/shinyapps", dependencies = TRUE) }'
  - Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")'
  - Rscript -e 'devtools::install_deps(pkg = ".", dependencies = TRUE)'
script:
  - Rscript -e "shinyapps::setAccountInfo(name='sboysel', token='FC30770A1477096766683E51D133026C',
    secret=Sys.getenv('SHINYAPPS_SECRET'))"
  - Rscript -e "shinyapps::deployApp(appName = 'yaclta')"
notifications:
  email:
    on_success: change
    on_failure: change
